<?xml version="1.0"?>
<!DOCTYPE mame [
<!ELEMENT mame (game+)>
	<!ELEMENT game (description, year?, manufacturer, history?, biosset*, rom*, disk*, sample*, chip*, video?, sound?, input?, dipswitch*, driver?)>
		<!ATTLIST game name CDATA #REQUIRED>
		<!ATTLIST game runnable (yes|no) "yes">
		<!ATTLIST game cloneof CDATA #IMPLIED>
		<!ATTLIST game romof CDATA #IMPLIED>
		<!ATTLIST game sampleof CDATA #IMPLIED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT manufacturer (#PCDATA)>
		<!ELEMENT history (#PCDATA)>
		<!ELEMENT biosset EMPTY>
			<!ATTLIST biosset name CDATA #REQUIRED>
			<!ATTLIST biosset description CDATA #REQUIRED>
			<!ATTLIST biosset default (yes|no) "no">
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom bios CDATA #IMPLIED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom md5 CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom merge CDATA #IMPLIED>
			<!ATTLIST rom region CDATA #IMPLIED>
			<!ATTLIST rom offset CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good) "good">
			<!ATTLIST rom dispose (yes|no) "no">
			<!ATTLIST rom soundonly (yes|no) "no">
		<!ELEMENT disk EMPTY>
			<!ATTLIST disk name CDATA #REQUIRED>
			<!ATTLIST disk md5 CDATA #IMPLIED>
			<!ATTLIST disk sha1 CDATA #IMPLIED>
			<!ATTLIST disk region CDATA #IMPLIED>
			<!ATTLIST disk index CDATA #IMPLIED>
		<!ELEMENT sample EMPTY>
			<!ATTLIST sample name CDATA #REQUIRED>
		<!ELEMENT chip EMPTY>
			<!ATTLIST chip name CDATA #REQUIRED>
			<!ATTLIST chip type (cpu|audio) #REQUIRED>
			<!ATTLIST chip soundonly (yes|no) "no">
			<!ATTLIST chip clock CDATA #IMPLIED>
		<!ELEMENT video EMPTY>
			<!ATTLIST video screen (raster|vector) #REQUIRED>
			<!ATTLIST video orientation (vertical|horizontal) #REQUIRED>
			<!ATTLIST video width CDATA #IMPLIED>
			<!ATTLIST video height CDATA #IMPLIED>
			<!ATTLIST video aspectx CDATA #IMPLIED>
			<!ATTLIST video aspecty CDATA #IMPLIED>
			<!ATTLIST video refresh CDATA #REQUIRED>
		<!ELEMENT sound EMPTY>
			<!ATTLIST sound channels CDATA #REQUIRED>
		<!ELEMENT input EMPTY>
			<!ATTLIST input service (yes|no) "no">
			<!ATTLIST input tilt (yes|no) "no">
			<!ATTLIST input players CDATA #REQUIRED>
			<!ATTLIST input control CDATA #IMPLIED>
			<!ATTLIST input buttons CDATA #IMPLIED>
			<!ATTLIST input coins CDATA #IMPLIED>
		<!ELEMENT dipswitch (dipvalue*)>
			<!ATTLIST dipswitch name CDATA #REQUIRED>
			<!ELEMENT dipvalue EMPTY>
				<!ATTLIST dipvalue name CDATA #REQUIRED>
				<!ATTLIST dipvalue default (yes|no) "no">
		<!ELEMENT driver EMPTY>
			<!ATTLIST driver status (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver emulation (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver color (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver sound (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver graphic (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver cocktail (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver protection (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver palettesize CDATA #REQUIRED>
]>

<mame>
	<game name="cyberbal">
		<description>Cyberball (rev 4)</description>
		<year>1988</year>
		<manufacturer>Atari Games</manufacturer>
		<rom name="4123-1m.064" size="65536" crc="fb872740" sha1="15e6721d466fe56d7c97c6801e214b32803a0a0d" region="cpu1" offset="0"/>
		<rom name="4124-1kl.064" size="65536" crc="87babad9" sha1="acdc6b5976445e203de19eb03697e307fe6da77d" region="cpu1" offset="1"/>
		<rom name="2131-2f.064" size="65536" crc="bd7e3d84" sha1="f87878042fc79fa3883136b31ac15ddc22c6023c" region="cpu2" offset="10000"/>
		<rom name="2127-3cd.064" size="65536" crc="3e5feb1f" sha1="9f92f496adbdf74e394e0d710d6471b9666ba5e5" region="cpu3" offset="0"/>
		<rom name="2128-1b.064" size="65536" crc="4e642cc3" sha1="f708b6dd4360380bb10059d66df66b07966210b4" region="cpu3" offset="1"/>
		<rom name="1129-1cd.064" size="65536" crc="db11d2f0" sha1="da9f49af533cbc732b17699040c7930070a90644" region="cpu3" offset="20000"/>
		<rom name="1130-3b.064" size="65536" crc="fd86b8aa" sha1="46310efed762632ed176a08aaec41e48aad41cc1" region="cpu3" offset="20001"/>
		<rom name="1132-3cd.064" size="65536" crc="ca5ce8d8" sha1="69dc83d43d8c9dc7ce3207e70f48fcfc5ddda0cc" region="cpu4" offset="0"/>
		<rom name="1133-1b.064" size="65536" crc="ffeb8746" sha1="0d8d28b2d997ff3cf01b4ef25b75fa5a69754af4" region="cpu4" offset="1"/>
		<rom name="1134-1cd.064" size="65536" crc="bcbd4c00" sha1="f0bfcdf0b5491e15872b543e99b834ae384cbf18" region="cpu4" offset="20000"/>
		<rom name="1135-3b.064" size="65536" crc="d520f560" sha1="fb0b8d021458379188c424a343622c46ad74edaa" region="cpu4" offset="20001"/>
		<rom name="1105-15a.064" size="65536" crc="e770eb3e" sha1="e9f9e9e05774005c8be3bbdc19985b59a0081ef4" region="gfx1" dispose="yes" offset="0"/>
		<rom name="1109-16a.064" size="65536" crc="40db00da" sha1="d92d856b06f6ba11621ba7aab3d40653b3c70159" region="gfx1" dispose="yes" offset="10000"/>
		<rom name="2113-18a.064" size="65536" crc="52bb08fb" sha1="08caa156923daf444e0caafb2cdff0704c90ef1f" region="gfx1" dispose="yes" offset="20000"/>
		<rom name="1117-19a.064" size="65536" crc="0a11d877" sha1="876cbeffd815c084d7cbd937067d65c04aeebce5" region="gfx1" dispose="yes" offset="30000"/>
		<rom name="1106-11a.064" size="65536" crc="6f53c7c1" sha1="5856d714c3af338be58156b404fb1e5a89c24cf9" region="gfx1" dispose="yes" offset="50000"/>
		<rom name="1110-12a.064" size="65536" crc="5de609e5" sha1="bbea36a4cbbfeab113925951ef097673eddf26a8" region="gfx1" dispose="yes" offset="60000"/>
		<rom name="2114-13a.064" size="65536" crc="e6f95010" sha1="42b14cf0dadfab9ce1032385fd21339b46edcfc2" region="gfx1" dispose="yes" offset="70000"/>
		<rom name="1118-14a.064" size="65536" crc="47f56ced" sha1="62e80191e1879ffb6c736aec004bbc30a366363f" region="gfx1" dispose="yes" offset="80000"/>
		<rom name="1107-15c.064" size="65536" crc="c8f1f7ff" sha1="2e0374901871d66a243f87bc4b9cbdde5505f0ec" region="gfx1" dispose="yes" offset="a0000"/>
		<rom name="1111-16c.064" size="65536" crc="6bf0bf98" sha1="7d2b3b61da3749b352a6bf3f1ae1cb736b5b8386" region="gfx1" dispose="yes" offset="b0000"/>
		<rom name="2115-18c.064" size="65536" crc="c3168603" sha1="43e00fc739d1b3dd6d925bad63058fe74c1efc74" region="gfx1" dispose="yes" offset="c0000"/>
		<rom name="1119-19c.064" size="65536" crc="7ff29d09" sha1="81458b058f0b037778f255b5afe94a44aba74829" region="gfx1" dispose="yes" offset="d0000"/>
		<rom name="1108-11c.064" size="65536" crc="99629412" sha1="53a91b2a1ac62259ec9f78421b22c7b22f4233d6" region="gfx1" dispose="yes" offset="f0000"/>
		<rom name="1112-12c.064" size="65536" crc="aa198cb7" sha1="aad4a60210289d2e5a93aac336ba995ed6ac4886" region="gfx1" dispose="yes" offset="100000"/>
		<rom name="2116-13c.064" size="65536" crc="6cf79a67" sha1="7f3271b575cf0b5033b5b19f0e71fae251040fc6" region="gfx1" dispose="yes" offset="110000"/>
		<rom name="1120-14c.064" size="65536" crc="40bdf767" sha1="c57aaea838abeaea1a0060c45c2f33c38a51edb3" region="gfx1" dispose="yes" offset="120000"/>
		<rom name="1101-9lm.064" size="65536" crc="a64b4da8" sha1="f68778adb56a1eb964acdbc7e9d690a8a83f170b" region="gfx2" dispose="yes" offset="0"/>
		<rom name="1102-8lm.064" size="65536" crc="ca91ec1b" sha1="970c64e19893503cae796daee63b2d7d08eaf551" region="gfx2" dispose="yes" offset="10000"/>
		<rom name="110311lm.064" size="65536" crc="ee29d1d1" sha1="2a7fea25728c66ce482de76299413ef5da01beef" region="gfx2" dispose="yes" offset="20000"/>
		<rom name="110410lm.064" size="65536" crc="882649f8" sha1="fbaea597b6e318234e41df245023643f448a4938" region="gfx2" dispose="yes" offset="30000"/>
		<rom name="1121-15n.064" size="65536" crc="0ca1e3b3" sha1="d934bc9a1def4404fb86175878404cbb18127a11" region="gfx3" dispose="yes" offset="0"/>
		<rom name="1122-16n.064" size="65536" crc="882f4e1c" sha1="f7517ff03502ff029fb375260a35e45414567433" region="gfx3" dispose="yes" offset="10000"/>
		<chip type="cpu" name="68000" clock="7159090"/>
		<chip type="cpu" name="M6502" clock="1789772"/>
		<chip type="cpu" name="68000" clock="7159090"/>
		<chip type="cpu" name="68000" clock="7159090"/>
		<chip type="audio" name="YM2151" clock="3579545"/>
		<chip type="audio" name="DAC"/>
		<chip type="audio" name="DAC"/>
		<video screen="raster" orientation="horizontal" width="1344" height="240" aspectx="8" aspecty="3" refresh="60.000000"/>
		<sound channels="2"/>
		<input players="4" control="joy8way" buttons="1" coins="4"/>
		<dipswitch name="Service Mode">
			<dipvalue name="Off" default="yes"/>
			<dipvalue name="On"/>
		</dipswitch>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" palettesize="4096"/>
	</game>
	<game name="cyberba2" cloneof="cyberbal" romof="cyberbal">
		<description>Cyberball (rev 2)</description>
		<year>1988</year>
		<manufacturer>Atari Games</manufacturer>
		<rom name="2123-1m.064" size="65536" crc="502676e8" sha1="c0f1f1ce50d3df21cb81244268faef6c303cdfab" region="cpu1" offset="0"/>
		<rom name="2124-1kl.064" size="65536" crc="30f55915" sha1="ab93ec46f282ab9a0cd47c989537a7e036975e3f" region="cpu1" offset="1"/>
		<rom name="2131-2f.064" merge="2131-2f.064" size="65536" crc="bd7e3d84" sha1="f87878042fc79fa3883136b31ac15ddc22c6023c" region="cpu2" offset="10000"/>
		<rom name="2127-3cd.064" merge="2127-3cd.064" size="65536" crc="3e5feb1f" sha1="9f92f496adbdf74e394e0d710d6471b9666ba5e5" region="cpu3" offset="0"/>
		<rom name="2128-1b.064" merge="2128-1b.064" size="65536" crc="4e642cc3" sha1="f708b6dd4360380bb10059d66df66b07966210b4" region="cpu3" offset="1"/>
		<rom name="1129-1cd.064" merge="1129-1cd.064" size="65536" crc="db11d2f0" sha1="da9f49af533cbc732b17699040c7930070a90644" region="cpu3" offset="20000"/>
		<rom name="1130-3b.064" merge="1130-3b.064" size="65536" crc="fd86b8aa" sha1="46310efed762632ed176a08aaec41e48aad41cc1" region="cpu3" offset="20001"/>
		<rom name="1132-3cd.064" merge="1132-3cd.064" size="65536" crc="ca5ce8d8" sha1="69dc83d43d8c9dc7ce3207e70f48fcfc5ddda0cc" region="cpu4" offset="0"/>
		<rom name="1133-1b.064" merge="1133-1b.064" size="65536" crc="ffeb8746" sha1="0d8d28b2d997ff3cf01b4ef25b75fa5a69754af4" region="cpu4" offset="1"/>
		<rom name="1134-1cd.064" merge="1134-1cd.064" size="65536" crc="bcbd4c00" sha1="f0bfcdf0b5491e15872b543e99b834ae384cbf18" region="cpu4" offset="20000"/>
		<rom name="1135-3b.064" merge="1135-3b.064" size="65536" crc="d520f560" sha1="fb0b8d021458379188c424a343622c46ad74edaa" region="cpu4" offset="20001"/>
		<rom name="1105-15a.064" merge="1105-15a.064" size="65536" crc="e770eb3e" sha1="e9f9e9e05774005c8be3bbdc19985b59a0081ef4" region="gfx1" dispose="yes" offset="0"/>
		<rom name="1109-16a.064" merge="1109-16a.064" size="65536" crc="40db00da" sha1="d92d856b06f6ba11621ba7aab3d40653b3c70159" region="gfx1" dispose="yes" offset="10000"/>
		<rom name="2113-18a.064" merge="2113-18a.064" size="65536" crc="52bb08fb" sha1="08caa156923daf444e0caafb2cdff0704c90ef1f" region="gfx1" dispose="yes" offset="20000"/>
		<rom name="1117-19a.064" merge="1117-19a.064" size="65536" crc="0a11d877" sha1="876cbeffd815c084d7cbd937067d65c04aeebce5" region="gfx1" dispose="yes" offset="30000"/>
		<rom name="1106-11a.064" merge="1106-11a.064" size="65536" crc="6f53c7c1" sha1="5856d714c3af338be58156b404fb1e5a89c24cf9" region="gfx1" dispose="yes" offset="50000"/>
		<rom name="1110-12a.064" merge="1110-12a.064" size="65536" crc="5de609e5" sha1="bbea36a4cbbfeab113925951ef097673eddf26a8" region="gfx1" dispose="yes" offset="60000"/>
		<rom name="2114-13a.064" merge="2114-13a.064" size="65536" crc="e6f95010" sha1="42b14cf0dadfab9ce1032385fd21339b46edcfc2" region="gfx1" dispose="yes" offset="70000"/>
		<rom name="1118-14a.064" merge="1118-14a.064" size="65536" crc="47f56ced" sha1="62e80191e1879ffb6c736aec004bbc30a366363f" region="gfx1" dispose="yes" offset="80000"/>
		<rom name="1107-15c.064" merge="1107-15c.064" size="65536" crc="c8f1f7ff" sha1="2e0374901871d66a243f87bc4b9cbdde5505f0ec" region="gfx1" dispose="yes" offset="a0000"/>
		<rom name="1111-16c.064" merge="1111-16c.064" size="65536" crc="6bf0bf98" sha1="7d2b3b61da3749b352a6bf3f1ae1cb736b5b8386" region="gfx1" dispose="yes" offset="b0000"/>
		<rom name="2115-18c.064" merge="2115-18c.064" size="65536" crc="c3168603" sha1="43e00fc739d1b3dd6d925bad63058fe74c1efc74" region="gfx1" dispose="yes" offset="c0000"/>
		<rom name="1119-19c.064" merge="1119-19c.064" size="65536" crc="7ff29d09" sha1="81458b058f0b037778f255b5afe94a44aba74829" region="gfx1" dispose="yes" offset="d0000"/>
		<rom name="1108-11c.064" merge="1108-11c.064" size="65536" crc="99629412" sha1="53a91b2a1ac62259ec9f78421b22c7b22f4233d6" region="gfx1" dispose="yes" offset="f0000"/>
		<rom name="1112-12c.064" merge="1112-12c.064" size="65536" crc="aa198cb7" sha1="aad4a60210289d2e5a93aac336ba995ed6ac4886" region="gfx1" dispose="yes" offset="100000"/>
		<rom name="2116-13c.064" merge="2116-13c.064" size="65536" crc="6cf79a67" sha1="7f3271b575cf0b5033b5b19f0e71fae251040fc6" region="gfx1" dispose="yes" offset="110000"/>
		<rom name="1120-14c.064" merge="1120-14c.064" size="65536" crc="40bdf767" sha1="c57aaea838abeaea1a0060c45c2f33c38a51edb3" region="gfx1" dispose="yes" offset="120000"/>
		<rom name="1101-9lm.064" merge="1101-9lm.064" size="65536" crc="a64b4da8" sha1="f68778adb56a1eb964acdbc7e9d690a8a83f170b" region="gfx2" dispose="yes" offset="0"/>
		<rom name="1102-8lm.064" merge="1102-8lm.064" size="65536" crc="ca91ec1b" sha1="970c64e19893503cae796daee63b2d7d08eaf551" region="gfx2" dispose="yes" offset="10000"/>
		<rom name="110311lm.064" merge="110311lm.064" size="65536" crc="ee29d1d1" sha1="2a7fea25728c66ce482de76299413ef5da01beef" region="gfx2" dispose="yes" offset="20000"/>
		<rom name="110410lm.064" merge="110410lm.064" size="65536" crc="882649f8" sha1="fbaea597b6e318234e41df245023643f448a4938" region="gfx2" dispose="yes" offset="30000"/>
		<rom name="1121-15n.064" merge="1121-15n.064" size="65536" crc="0ca1e3b3" sha1="d934bc9a1def4404fb86175878404cbb18127a11" region="gfx3" dispose="yes" offset="0"/>
		<rom name="1122-16n.064" merge="1122-16n.064" size="65536" crc="882f4e1c" sha1="f7517ff03502ff029fb375260a35e45414567433" region="gfx3" dispose="yes" offset="10000"/>
		<chip type="cpu" name="68000" clock="7159090"/>
		<chip type="cpu" name="M6502" clock="1789772"/>
		<chip type="cpu" name="68000" clock="7159090"/>
		<chip type="cpu" name="68000" clock="7159090"/>
		<chip type="audio" name="YM2151" clock="3579545"/>
		<chip type="audio" name="DAC"/>
		<chip type="audio" name="DAC"/>
		<video screen="raster" orientation="horizontal" width="1344" height="240" aspectx="8" aspecty="3" refresh="60.000000"/>
		<sound channels="2"/>
		<input players="4" control="joy8way" buttons="1" coins="4"/>
		<dipswitch name="Service Mode">
			<dipvalue name="Off" default="yes"/>
			<dipvalue name="On"/>
		</dipswitch>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" palettesize="4096"/>
	</game>
	<game name="cyberbap" cloneof="cyberbal" romof="cyberbal">
		<description>Cyberball (prototype)</description>
		<year>1988</year>
		<manufacturer>Atari Games</manufacturer>
		<rom name="0123-1m.064" size="65536" crc="59bac810" sha1="d4742b2b554c2ad62a2ea7152db3f06a06cddd67" region="cpu1" offset="0"/>
		<rom name="0124-1kl.064" size="65536" crc="e48e6dd3" sha1="4d45bc66c0a3eb1174db7f19c5dee54dabad68f3" region="cpu1" offset="1"/>
		<rom name="0131-2f.064" size="65536" crc="c72b71ce" sha1="6d3d8f437cf55ccaaa4490daa69f402902944686" region="cpu2" offset="10000"/>
		<rom name="0127-3cd.064" size="65536" crc="37ad3420" sha1="e9c1ea59f5f9a133822a49027b4abf02af855ca2" region="cpu3" offset="0"/>
		<rom name="0128-1b.064" size="65536" crc="d89aa8af" sha1="b9faca1a775c1d699335a5ac0e1d25e8370c02a7" region="cpu3" offset="1"/>
		<rom name="1129-1cd.064" merge="1129-1cd.064" size="65536" crc="db11d2f0" sha1="da9f49af533cbc732b17699040c7930070a90644" region="cpu3" offset="20000"/>
		<rom name="1130-3b.064" merge="1130-3b.064" size="65536" crc="fd86b8aa" sha1="46310efed762632ed176a08aaec41e48aad41cc1" region="cpu3" offset="20001"/>
		<rom name="0132-3cd.064" size="65536" crc="392a442c" sha1="e108456167f433808b452edb3351d283b5cf7a50" region="cpu4" offset="0"/>
		<rom name="0133-1b.064" size="65536" crc="a0a11cf9" sha1="b28a379cb49d051b6ccff877255409e1231d3030" region="cpu4" offset="1"/>
		<rom name="1134-1cd.064" merge="1134-1cd.064" size="65536" crc="bcbd4c00" sha1="f0bfcdf0b5491e15872b543e99b834ae384cbf18" region="cpu4" offset="20000"/>
		<rom name="1135-3b.064" merge="1135-3b.064" size="65536" crc="d520f560" sha1="fb0b8d021458379188c424a343622c46ad74edaa" region="cpu4" offset="20001"/>
		<rom name="1105-15a.064" merge="1105-15a.064" size="65536" crc="e770eb3e" sha1="e9f9e9e05774005c8be3bbdc19985b59a0081ef4" region="gfx1" dispose="yes" offset="0"/>
		<rom name="1109-16a.064" merge="1109-16a.064" size="65536" crc="40db00da" sha1="d92d856b06f6ba11621ba7aab3d40653b3c70159" region="gfx1" dispose="yes" offset="10000"/>
		<rom name="2113-18a.064" merge="2113-18a.064" size="65536" crc="52bb08fb" sha1="08caa156923daf444e0caafb2cdff0704c90ef1f" region="gfx1" dispose="yes" offset="20000"/>
		<rom name="1117-19a.064" merge="1117-19a.064" size="65536" crc="0a11d877" sha1="876cbeffd815c084d7cbd937067d65c04aeebce5" region="gfx1" dispose="yes" offset="30000"/>
		<rom name="1106-11a.064" merge="1106-11a.064" size="65536" crc="6f53c7c1" sha1="5856d714c3af338be58156b404fb1e5a89c24cf9" region="gfx1" dispose="yes" offset="50000"/>
		<rom name="1110-12a.064" merge="1110-12a.064" size="65536" crc="5de609e5" sha1="bbea36a4cbbfeab113925951ef097673eddf26a8" region="gfx1" dispose="yes" offset="60000"/>
		<rom name="2114-13a.064" merge="2114-13a.064" size="65536" crc="e6f95010" sha1="42b14cf0dadfab9ce1032385fd21339b46edcfc2" region="gfx1" dispose="yes" offset="70000"/>
		<rom name="1118-14a.064" merge="1118-14a.064" size="65536" crc="47f56ced" sha1="62e80191e1879ffb6c736aec004bbc30a366363f" region="gfx1" dispose="yes" offset="80000"/>
		<rom name="1107-15c.064" merge="1107-15c.064" size="65536" crc="c8f1f7ff" sha1="2e0374901871d66a243f87bc4b9cbdde5505f0ec" region="gfx1" dispose="yes" offset="a0000"/>
		<rom name="1111-16c.064" merge="1111-16c.064" size="65536" crc="6bf0bf98" sha1="7d2b3b61da3749b352a6bf3f1ae1cb736b5b8386" region="gfx1" dispose="yes" offset="b0000"/>
		<rom name="2115-18c.064" merge="2115-18c.064" size="65536" crc="c3168603" sha1="43e00fc739d1b3dd6d925bad63058fe74c1efc74" region="gfx1" dispose="yes" offset="c0000"/>
		<rom name="1119-19c.064" merge="1119-19c.064" size="65536" crc="7ff29d09" sha1="81458b058f0b037778f255b5afe94a44aba74829" region="gfx1" dispose="yes" offset="d0000"/>
		<rom name="1108-11c.064" merge="1108-11c.064" size="65536" crc="99629412" sha1="53a91b2a1ac62259ec9f78421b22c7b22f4233d6" region="gfx1" dispose="yes" offset="f0000"/>
		<rom name="1112-12c.064" merge="1112-12c.064" size="65536" crc="aa198cb7" sha1="aad4a60210289d2e5a93aac336ba995ed6ac4886" region="gfx1" dispose="yes" offset="100000"/>
		<rom name="2116-13c.064" merge="2116-13c.064" size="65536" crc="6cf79a67" sha1="7f3271b575cf0b5033b5b19f0e71fae251040fc6" region="gfx1" dispose="yes" offset="110000"/>
		<rom name="1120-14c.064" merge="1120-14c.064" size="65536" crc="40bdf767" sha1="c57aaea838abeaea1a0060c45c2f33c38a51edb3" region="gfx1" dispose="yes" offset="120000"/>
		<rom name="1101-9lm.064" merge="1101-9lm.064" size="65536" crc="a64b4da8" sha1="f68778adb56a1eb964acdbc7e9d690a8a83f170b" region="gfx2" dispose="yes" offset="0"/>
		<rom name="1102-8lm.064" merge="1102-8lm.064" size="65536" crc="ca91ec1b" sha1="970c64e19893503cae796daee63b2d7d08eaf551" region="gfx2" dispose="yes" offset="10000"/>
		<rom name="110311lm.064" merge="110311lm.064" size="65536" crc="ee29d1d1" sha1="2a7fea25728c66ce482de76299413ef5da01beef" region="gfx2" dispose="yes" offset="20000"/>
		<rom name="110410lm.064" merge="110410lm.064" size="65536" crc="882649f8" sha1="fbaea597b6e318234e41df245023643f448a4938" region="gfx2" dispose="yes" offset="30000"/>
		<rom name="1121-15n.064" merge="1121-15n.064" size="65536" crc="0ca1e3b3" sha1="d934bc9a1def4404fb86175878404cbb18127a11" region="gfx3" dispose="yes" offset="0"/>
		<rom name="1122-16n.064" merge="1122-16n.064" size="65536" crc="882f4e1c" sha1="f7517ff03502ff029fb375260a35e45414567433" region="gfx3" dispose="yes" offset="10000"/>
		<chip type="cpu" name="68000" clock="7159090"/>
		<chip type="cpu" name="M6502" clock="1789772"/>
		<chip type="cpu" name="68000" clock="7159090"/>
		<chip type="cpu" name="68000" clock="7159090"/>
		<chip type="audio" name="YM2151" clock="3579545"/>
		<chip type="audio" name="DAC"/>
		<chip type="audio" name="DAC"/>
		<video screen="raster" orientation="horizontal" width="1344" height="240" aspectx="8" aspecty="3" refresh="60.000000"/>
		<sound channels="2"/>
		<input players="4" control="joy8way" buttons="1" coins="4"/>
		<dipswitch name="Service Mode">
			<dipvalue name="Off" default="yes"/>
			<dipvalue name="On"/>
		</dipswitch>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" palettesize="4096"/>
	</game>
	<game name="cyberb2p" cloneof="cyberbal" romof="cyberbal">
		<description>Cyberball 2072 (2 player, rev 4)</description>
		<year>1989</year>
		<manufacturer>Atari Games</manufacturer>
		<rom name="4019-10c.071" size="65536" crc="20c6b09c" sha1="b12f9247621fe0242171140256b7b92c996dcb19" region="cpu1" offset="0"/>
		<rom name="4020-10d.071" size="65536" crc="eaa6c524" sha1="0bc48dca1f10fbb3dec441d06f447637b6c70356" region="cpu1" offset="1"/>
		<rom name="4021-21c.071" size="65536" crc="89ffa885" sha1="d276209fd72c753d23571464e51d701a54cc3e0e" region="cpu1" offset="20000"/>
		<rom name="4022-21d.071" size="65536" crc="35da3402" sha1="7b51e0fb202699457a3b8e2bd8a68fef0889435f" region="cpu1" offset="20001"/>
		<rom name="2023-15c.071" size="65536" crc="e541b08f" sha1="345843209b02fb50cb08f55f80036046873b834f" region="cpu1" offset="40000"/>
		<rom name="2024-15d.071" size="65536" crc="5a77ee95" sha1="441a45a358eb78cc140c96dc4c42b30e1929ad07" region="cpu1" offset="40001"/>
		<rom name="1025-27c.071" size="65536" crc="95ff68c6" sha1="43f716a4c44fe1a38fcc6e2600bac948bb603504" region="cpu1" offset="60000"/>
		<rom name="1026-27d.071" size="65536" crc="f61c4898" sha1="9e4a14eac6d197f63c3392af3d804e81c034cb09" region="cpu1" offset="60001"/>
		<rom name="1042-1b.071" size="65536" crc="e63cf125" sha1="449880f561660ba67ac2d7f8ce6333768e0ae0be" region="cpu2" offset="10000"/>
		<rom name="1001-55l.071" size="131072" crc="586ba107" sha1="f15d4489f5834ea5fe695f43cb9d1c2401179870" region="gfx1" dispose="yes" offset="0"/>
		<rom name="1005-43l.071" size="131072" crc="a53e6248" sha1="4f2466c6af74a5498468801b1de7adfc34873d5d" region="gfx1" dispose="yes" offset="20000"/>
		<rom name="1032-18a.071" size="65536" crc="131f52a0" sha1="fa50ea82d26c36dd6a135e22dee509676d1dfe86" region="gfx1" dispose="yes" offset="40000"/>
		<rom name="1002-55n.071" size="131072" crc="0f71f86c" sha1="783f33ba5cc1b2f0c42b8515b1cf8b6a2270acb9" region="gfx1" dispose="yes" offset="50000"/>
		<rom name="1006-43n.071" size="131072" crc="df0ab373" sha1="3d511236eb55a773c66643158c6ef2c4dce53b68" region="gfx1" dispose="yes" offset="70000"/>
		<rom name="1033-13a.071" size="65536" crc="b6270943" sha1="356e58dfd30c6db15264eceacef0eacda99aabae" region="gfx1" dispose="yes" offset="90000"/>
		<rom name="1003-90l.071" size="131072" crc="1cf373a2" sha1="c8538855bb82fc03e26c64fc9008fbd0c66fac09" region="gfx1" dispose="yes" offset="a0000"/>
		<rom name="1007-78l.071" size="131072" crc="f2ffab24" sha1="6c5c90a9d9b342414a0d6258dd27b0b84bf0af0b" region="gfx1" dispose="yes" offset="c0000"/>
		<rom name="1034-18c.071" size="65536" crc="6514f0bd" sha1="e887dfb9e0334a7d94e7124cea6101d9ac7f0ab6" region="gfx1" dispose="yes" offset="e0000"/>
		<rom name="1004-90n.071" size="131072" crc="537f6de3" sha1="d5d385c3ff07aaef7bd3bd4f6c8066948a45ce9c" region="gfx1" dispose="yes" offset="f0000"/>
		<rom name="1008-78n.071" size="131072" crc="78525bbb" sha1="98ece6c0672cb60f818b8005c76cc4ae1d24b104" region="gfx1" dispose="yes" offset="110000"/>
		<rom name="1035-13c.071" size="65536" crc="1be3e5c8" sha1="1a4d0e0d53b902c28977c8598e363c7b61c9c1c8" region="gfx1" dispose="yes" offset="130000"/>
		<rom name="1013-10k.071" size="65536" crc="cdf6e3d6" sha1="476644065b82e2ea553dfb51844c0bbf3313c481" region="gfx2" dispose="yes" offset="0"/>
		<rom name="1014-16f.071" size="65536" crc="ec2fef3e" sha1="07ed472fa1723ebf82d608667df70511a50dca3e" region="gfx2" dispose="yes" offset="10000"/>
		<rom name="1015-16k.071" size="65536" crc="e866848f" sha1="35b438dcc1947151a7aafe919b9adf33d7a8fb77" region="gfx2" dispose="yes" offset="20000"/>
		<rom name="1016-10f.071" size="65536" crc="9b9a393c" sha1="db4ceb33756bab0ac7bea30e6c7345d06a0f4aa2" region="gfx2" dispose="yes" offset="30000"/>
		<rom name="1017-32n.071" size="65536" crc="a4c116f9" sha1="fc7becef35306ef99ffbd0cd9202759352eb6cbe" region="gfx3" dispose="yes" offset="0"/>
		<rom name="1018-32l.071" size="65536" crc="e25d7847" sha1="3821c62f9bdc04eb774c2210a84e26b36f2e163d" region="gfx3" dispose="yes" offset="10000"/>
		<rom name="1043-7k.071" size="65536" crc="94f24575" sha1="b93b326e15cd328362ce409b7c0cc42b8a28c701" region="sound1" offset="0"/>
		<rom name="1044-7j.071" size="65536" crc="87208e1e" sha1="3647867ddc36df7633ed740c0b9365a979ef5621" region="sound1" offset="10000"/>
		<rom name="1045-7e.071" size="65536" crc="f82558b9" sha1="afbecccc6203db9bdcf60638e0f4e95040d7aaf2" region="sound1" offset="20000"/>
		<rom name="1046-7d.071" size="65536" crc="d96437ad" sha1="b0b5cd75de4048e54b9d7d09a75381eb73c22ee1" region="sound1" offset="30000"/>
		<chip type="cpu" name="68000" clock="7159090"/>
		<chip type="cpu" name="M6502" clock="1789500"/>
		<chip type="audio" name="YM2151" clock="3579000"/>
		<chip type="audio" name="MSM6295" clock="9037"/>
		<video screen="raster" orientation="horizontal" width="672" height="240" aspectx="4" aspecty="3" refresh="60.000000"/>
		<sound channels="1"/>
		<input players="2" control="joy8way" buttons="1" coins="3"/>
		<dipswitch name="Service Mode">
			<dipvalue name="Off" default="yes"/>
			<dipvalue name="On"/>
		</dipswitch>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" palettesize="2048"/>
	</game>
	<game name="cyberb23" cloneof="cyberbal" romof="cyberbal">
		<description>Cyberball 2072 (2 player, rev 3)</description>
		<year>1989</year>
		<manufacturer>Atari Games</manufacturer>
		<rom name="3019-10c.071" size="65536" crc="029f8cb6" sha1="528ab6357592313b41964102c14b90862c05f248" region="cpu1" offset="0"/>
		<rom name="3020-10d.071" size="65536" crc="1871b344" sha1="2b6f2f4760af0f0e1e0b6cb34017dcdca7635e60" region="cpu1" offset="1"/>
		<rom name="3021-21c.071" size="65536" crc="fd7ebead" sha1="4118c865897c7a9f73de200ea9766fe190547606" region="cpu1" offset="20000"/>
		<rom name="3022-21d.071" size="65536" crc="173ccad4" sha1="4a8d2751b338dbb6dc556dfab13799561fee4836" region="cpu1" offset="20001"/>
		<rom name="2023-15c.071" size="65536" crc="e541b08f" sha1="345843209b02fb50cb08f55f80036046873b834f" region="cpu1" offset="40000"/>
		<rom name="2024-15d.071" size="65536" crc="5a77ee95" sha1="441a45a358eb78cc140c96dc4c42b30e1929ad07" region="cpu1" offset="40001"/>
		<rom name="1025-27c.071" size="65536" crc="95ff68c6" sha1="43f716a4c44fe1a38fcc6e2600bac948bb603504" region="cpu1" offset="60000"/>
		<rom name="1026-27d.071" size="65536" crc="f61c4898" sha1="9e4a14eac6d197f63c3392af3d804e81c034cb09" region="cpu1" offset="60001"/>
		<rom name="1042-1b.071" size="65536" crc="e63cf125" sha1="449880f561660ba67ac2d7f8ce6333768e0ae0be" region="cpu2" offset="10000"/>
		<rom name="1001-55l.071" size="131072" crc="586ba107" sha1="f15d4489f5834ea5fe695f43cb9d1c2401179870" region="gfx1" dispose="yes" offset="0"/>
		<rom name="1005-43l.071" size="131072" crc="a53e6248" sha1="4f2466c6af74a5498468801b1de7adfc34873d5d" region="gfx1" dispose="yes" offset="20000"/>
		<rom name="1032-18a.071" size="65536" crc="131f52a0" sha1="fa50ea82d26c36dd6a135e22dee509676d1dfe86" region="gfx1" dispose="yes" offset="40000"/>
		<rom name="1002-55n.071" size="131072" crc="0f71f86c" sha1="783f33ba5cc1b2f0c42b8515b1cf8b6a2270acb9" region="gfx1" dispose="yes" offset="50000"/>
		<rom name="1006-43n.071" size="131072" crc="df0ab373" sha1="3d511236eb55a773c66643158c6ef2c4dce53b68" region="gfx1" dispose="yes" offset="70000"/>
		<rom name="1033-13a.071" size="65536" crc="b6270943" sha1="356e58dfd30c6db15264eceacef0eacda99aabae" region="gfx1" dispose="yes" offset="90000"/>
		<rom name="1003-90l.071" size="131072" crc="1cf373a2" sha1="c8538855bb82fc03e26c64fc9008fbd0c66fac09" region="gfx1" dispose="yes" offset="a0000"/>
		<rom name="1007-78l.071" size="131072" crc="f2ffab24" sha1="6c5c90a9d9b342414a0d6258dd27b0b84bf0af0b" region="gfx1" dispose="yes" offset="c0000"/>
		<rom name="1034-18c.071" size="65536" crc="6514f0bd" sha1="e887dfb9e0334a7d94e7124cea6101d9ac7f0ab6" region="gfx1" dispose="yes" offset="e0000"/>
		<rom name="1004-90n.071" size="131072" crc="537f6de3" sha1="d5d385c3ff07aaef7bd3bd4f6c8066948a45ce9c" region="gfx1" dispose="yes" offset="f0000"/>
		<rom name="1008-78n.071" size="131072" crc="78525bbb" sha1="98ece6c0672cb60f818b8005c76cc4ae1d24b104" region="gfx1" dispose="yes" offset="110000"/>
		<rom name="1035-13c.071" size="65536" crc="1be3e5c8" sha1="1a4d0e0d53b902c28977c8598e363c7b61c9c1c8" region="gfx1" dispose="yes" offset="130000"/>
		<rom name="1013-10k.071" size="65536" crc="cdf6e3d6" sha1="476644065b82e2ea553dfb51844c0bbf3313c481" region="gfx2" dispose="yes" offset="0"/>
		<rom name="1014-16f.071" size="65536" crc="ec2fef3e" sha1="07ed472fa1723ebf82d608667df70511a50dca3e" region="gfx2" dispose="yes" offset="10000"/>
		<rom name="1015-16k.071" size="65536" crc="e866848f" sha1="35b438dcc1947151a7aafe919b9adf33d7a8fb77" region="gfx2" dispose="yes" offset="20000"/>